//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_page
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinusVote
    {
        public int Id { get; set; }
        public Nullable<int> answerId { get; set; }
        public Nullable<int> userId { get; set; }
        public string disabled { get; set; }
        public string color { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual User User { get; set; }
    }
}
