//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_page
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionTypeAsk
    {
        public int Id { get; set; }
        public int QuestionTypeId { get; set; }
        public int AskId { get; set; }
    
        public virtual Ask Ask { get; set; }
        public virtual QuestionType QuestionType { get; set; }
    }
}
